/**
 * Project YooLearn
 * File user.types
 * Path app/redux/user
 * Created by BRICE ZELE
 * Date: 26/08/2021
 */
const CourrierActionsType = {
    GET_ALL_COURRIER_PENDING: 'GET_ALL_COURRIER_PENDING',
    GET_ALL_COURRIER_SUCCESS: 'GET_ALL_COURRIER_SUCCESS',
    GET_ALL_COURRIER_ERROR: 'GET_ALL_COURRIER_ERROR',
    GET_ALL_COURRIER_RESET: 'GET_ALL_COURRIER_RESET',

    CREATE_COURRIER_PENDING: 'CREATE_COURRIER_PENDING',
    CREATE_COURRIER_SUCCESS: 'CREATE_COURRIER_SUCCESS',
    CREATE_COURRIER_ERROR: 'CREATE_COURRIER_ERROR',
    CREATE_COURRIER_RESET: 'CREATE_COURRIER_RESET',

    UPDATE_COURRIER_PENDING: 'UPDATE_COURRIER_PENDING',
    UPDATE_COURRIER_SUCCESS: 'UPDATE_COURRIER_SUCCESS',
    UPDATE_COURRIER_ERROR: 'UPDATE_COURRIER_ERROR',
    UPDATE_COURRIER_RESET: 'UPDATE_COURRIER_RESET',
};
export default CourrierActionsType;
