/**
 * Project YooLearn
 * File user.types
 * Path app/redux/user
 * Created by BRICE ZELE
 * Date: 26/08/2021
 */
const SocietyActionsType = {
    CREATE_SOCIETY_PENDING: 'CREATE_SOCIETY_PENDING',
    CREATE_SOCIETY_SUCCESS: 'CREATE_SOCIETY_SUCCESS',
    CREATE_SOCIETY_ERROR: 'CREATE_SOCIETY_ERROR',
    CREATE_SOCIETY_RESET: 'CREATE_SOCIETY_RESET',

    GET_ALL_SOCIETY_PENDING: 'GET_ALL_SOCIETY_PENDING',
    GET_ALL_SOCIETY_SUCCESS: 'GET_ALL_SOCIETY_SUCCESS',
    GET_ALL_SOCIETY_ERROR: 'GET_ALL_SOCIETY_ERROR',
    GET_ALL_SOCIETY_RESET: 'GET_ALL_SOCIETY_RESET',

    UPDATE_SOCIETY_PENDING: 'UPDATE_SOCIETY_PENDING',
    UPDATE_SOCIETY_SUCCESS: 'UPDATE_SOCIETY_SUCCESS',
    UPDATE_SOCIETY_ERROR: 'UPDATE_SOCIETY_ERROR',
    UPDATE_SOCIETY_RESET: 'UPDATE_SOCIETY_RESET',

};
export default SocietyActionsType;
