/**
 * Project YooLearn
 * File user.types
 * Path app/redux/user
 * Created by BRICE ZELE
 * Date: 26/08/2021
 */
const DepartmentActionsType = {
    CREATE_DEPARTMENT_PENDING: 'CREATE_DEPARTMENT_PENDING',
    CREATE_DEPARTMENT_SUCCESS: 'CREATE_DEPARTMENT_SUCCESS',
    CREATE_DEPARTMENT_ERROR: 'CREATE_DEPARTMENT_ERROR',
    CREATE_DEPARTMENT_RESET: 'CREATE_DEPARTMENT_RESET',

    GET_ALL_DEPARTMENT_PENDING: 'GET_ALL_DEPARTMENT_PENDING',
    GET_ALL_DEPARTMENT_SUCCESS: 'GET_ALL_DEPARTMENT_SUCCESS',
    GET_ALL_DEPARTMENT_ERROR: 'GET_ALL_DEPARTMENT_ERROR',
    GET_ALL_DEPARTMENT_RESET: 'GET_ALL_DEPARTMENT_RESET',

    UPDATE_DEPARTMENT_PENDING: 'UPDATE_DEPARTMENT_PENDING',
    UPDATE_DEPARTMENT_SUCCESS: 'UPDATE_DEPARTMENT_SUCCESS',
    UPDATE_DEPARTMENT_ERROR: 'UPDATE_DEPARTMENT_ERROR',
    UPDATE_DEPARTMENT_RESET: 'UPDATE_DEPARTMENT_RESET',

};
export default DepartmentActionsType;
